/**
 * KB semantic index — Phase 4 of the AI Reviewer Maturity Rollout.
 *
 * Crawls BookStack pages, embeds their plaintext content via OpenAI's
 * text-embedding-3-small (1536 dims), and persists the vectors as packed
 * Float32 BLOBs in `kb_page_embeddings`. At query time the entire index
 * is loaded into memory (cheap — a few hundred pages × 6KB) and ranked
 * by cosine similarity against an embedded query string.
 *
 * Cost notes (April 2026 pricing):
 *   - text-embedding-3-small: $0.02 per 1M tokens
 *   - One-time crawl of a few hundred pages: well under $0.10
 *   - Per-review query embedding: ~$0.0001
 *
 * The embeddings table is a CACHE. Wiping it just makes the next crawl
 * re-embed everything from scratch. A page's content_sha gates whether
 * we re-embed on subsequent crawls — pages whose plaintext is unchanged
 * are skipped.
 *
 * Used as the THIRD layer of grounding inside AIReviewerService.searchKb()
 * (after deterministic playbook URLs and BookStack full-text search).
 */

import { createHash } from 'crypto';
import prisma from '../config/prisma';
import logger from '../config/logger';
import bookstackService from './BookStackService';
import { getOpenAIClient, isOpenAIConfigured } from './ai/OpenAIClient';

const EMBEDDING_MODEL = 'text-embedding-3-small';
const EMBEDDING_DIMS = 1536;
/** OpenAI embedding endpoint allows up to ~8192 tokens; 8000 chars is a safe-ish truncation. */
const MAX_EMBED_CHARS = 8000;

interface IndexedPage {
  pageId: number;
  pageName: string;
  pageUrl: string;
  bookSlug: string;
  embedding: Float32Array;
}

export interface KbSemanticHit {
  id: number;
  name: string;
  url: string;
  score: number;
}

export interface CrawlSummary {
  pages_total: number;
  pages_new: number;
  pages_updated: number;
  pages_unchanged: number;
  pages_skipped: number;
  pages_errored: number;
  approx_cost_usd: number;
  elapsed_ms: number;
}

class KbIndexService {
  /** In-memory cache of all embeddings. Loaded lazily; reset() clears it. */
  private cache: IndexedPage[] | null = null;

  isConfigured(): boolean {
    return isOpenAIConfigured() && bookstackService.isConfigured();
  }

  /** Drop the in-memory cache so the next semanticSearch reloads from MySQL. */
  reset(): void {
    this.cache = null;
  }

  /**
   * Crawl every BookStack page accessible to the API token, embed those
   * whose plaintext SHA differs from the cached row, and upsert the
   * embeddings table. Returns a summary suitable for CLI display.
   *
   * Use { force: true } to re-embed every page regardless of content hash
   * (e.g. after switching embedding models).
   */
  async crawlAndIndex(opts: { force?: boolean } = {}): Promise<CrawlSummary> {
    if (!this.isConfigured()) {
      throw new Error('KbIndexService is not configured (need OPENAI_API_KEY and BookStack creds).');
    }
    const started = Date.now();
    const force = !!opts.force;

    // BookStack returns up to 100 per call. listPages doesn't paginate
    // for us, so loop until we get a short page.
    const allPages = await this.listAllPages();
    const books = await bookstackService.listBooks();
    const bookSlugById = new Map(books.map((b) => [b.id, b.slug]));

    // Build a {page_id → existing row} map so we can compare hashes.
    const existing = await prisma.kbPageEmbedding.findMany();
    const existingByPageId = new Map(existing.map((r) => [r.page_id, r]));

    const summary: CrawlSummary = {
      pages_total: allPages.length,
      pages_new: 0,
      pages_updated: 0,
      pages_unchanged: 0,
      pages_skipped: 0,
      pages_errored: 0,
      approx_cost_usd: 0,
      elapsed_ms: 0,
    };

    let totalChars = 0;
    for (const page of allPages) {
      try {
        if (page.draft || page.template) {
          summary.pages_skipped++;
          continue;
        }
        const content = await bookstackService.getPageContent(page.id, 'plaintext');
        const trimmed = content.slice(0, MAX_EMBED_CHARS);
        if (!trimmed.trim()) {
          summary.pages_skipped++;
          continue;
        }
        const sha = sha256(trimmed);
        const prior = existingByPageId.get(page.id);
        if (!force && prior && prior.content_sha === sha) {
          summary.pages_unchanged++;
          continue;
        }

        const embedding = await this.embedText(trimmed);
        const buf = packFloat32(embedding);
        const bookSlug = bookSlugById.get(page.book_id) ?? '';

        // Bytes column. Prisma's generated Bytes type is
        // Uint8Array<ArrayBuffer> (a stricter form than @types/node's
        // default Uint8Array<ArrayBufferLike>). The runtime value is
        // identical; cast via `any` only at the field assignment so the
        // rest of the file keeps a precise Uint8Array type.
        await prisma.kbPageEmbedding.upsert({
          where: { page_id: page.id },
          create: {
            page_id: page.id,
            page_name: page.name,
            page_url: bookstackPageUrl(bookSlug, page.slug),
            book_slug: bookSlug,
            content_sha: sha,
            embedding: buf as any,
            embedding_dims: EMBEDDING_DIMS,
            chars: trimmed.length,
            crawled_at: new Date(),
          },
          update: {
            page_name: page.name,
            page_url: bookstackPageUrl(bookSlug, page.slug),
            book_slug: bookSlug,
            content_sha: sha,
            embedding: buf as any,
            embedding_dims: EMBEDDING_DIMS,
            chars: trimmed.length,
            crawled_at: new Date(),
          },
        });

        totalChars += trimmed.length;
        if (prior) summary.pages_updated++;
        else summary.pages_new++;
      } catch (err) {
        summary.pages_errored++;
        logger.warn(`[kb-index] page_id=${page.id} (${page.name}) failed: ${(err as Error).message}`);
      }
    }

    // text-embedding-3-small: $0.02 / 1M tokens. Rough char→token ≈ 4.
    const tokens = totalChars / 4;
    summary.approx_cost_usd = (tokens / 1_000_000) * 0.02;
    summary.elapsed_ms = Date.now() - started;

    // Invalidate cache so next semanticSearch picks up the fresh vectors.
    this.reset();
    return summary;
  }

  /** How many embeddings are persisted right now. */
  async count(): Promise<number> {
    return prisma.kbPageEmbedding.count();
  }

  /**
   * Cosine-rank pages against a query string. Returns top-k by similarity.
   * Returns [] if the index is empty (callers should fall back to other
   * grounding layers, e.g. text search, in that case).
   */
  async semanticSearch(query: string, k = 5): Promise<KbSemanticHit[]> {
    if (!this.isConfigured()) return [];
    const trimmed = query.trim();
    if (!trimmed) return [];

    const index = await this.loadEmbeddings();
    if (index.length === 0) return [];

    const queryVec = await this.embedText(trimmed);
    // Both vectors are L2-normalized at insert/embed time below, so the
    // dot product equals cosine similarity. Massively cheaper than
    // computing magnitudes per pair.
    const scored = index.map((row) => ({
      id: row.pageId,
      name: row.pageName,
      url: row.pageUrl,
      score: dotProduct(queryVec, row.embedding),
    }));
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, k);
  }

  // ----- internals --------------------------------------------------------

  /** Load + cache the entire embedding table in memory (lazy, idempotent). */
  private async loadEmbeddings(): Promise<IndexedPage[]> {
    if (this.cache !== null) return this.cache;
    const rows = await prisma.kbPageEmbedding.findMany();
    this.cache = rows.map((r) => ({
      pageId: r.page_id,
      pageName: r.page_name,
      pageUrl: r.page_url,
      bookSlug: r.book_slug,
      embedding: unpackFloat32(r.embedding, r.embedding_dims),
    }));
    return this.cache;
  }

  /** Get a single L2-normalized embedding from OpenAI. */
  private async embedText(text: string): Promise<Float32Array> {
    const client = getOpenAIClient();
    const res = await client.embeddings.create({
      model: EMBEDDING_MODEL,
      input: text,
    });
    const raw = res.data[0]?.embedding ?? [];
    if (raw.length !== EMBEDDING_DIMS) {
      throw new Error(`Embedding dim mismatch: got ${raw.length}, expected ${EMBEDDING_DIMS}`);
    }
    const arr = new Float32Array(raw.length);
    for (let i = 0; i < raw.length; i++) arr[i] = raw[i];
    return l2Normalize(arr);
  }

  /** Walk BookStack page-list pagination until exhausted. */
  private async listAllPages(): Promise<{ id: number; name: string; slug: string; book_id: number; draft?: boolean; template?: boolean }[]> {
    const pageSize = 100;
    const out: { id: number; name: string; slug: string; book_id: number; draft?: boolean; template?: boolean }[] = [];
    let offset = 0;
    for (;;) {
      const batch = await bookstackService.listPages({ count: pageSize, offset });
      out.push(...batch);
      if (batch.length < pageSize) break;
      offset += pageSize;
      // Safety bound — BookStack instances with thousands of pages can
      // still index, but log if we're running away.
      if (offset > 10_000) {
        logger.warn(`[kb-index] crawl bailed at ${offset} pages (safety cap)`);
        break;
      }
    }
    return out;
  }
}

function bookstackPageUrl(bookSlug: string, pageSlug: string): string {
  // Reconstruct the canonical URL the same way BookStack does. Falls
  // back to a slug-only path if the book slug is missing — better than
  // an empty string.
  const base = (process.env.BOOKSTACK_BASE_URL ?? '').replace(/\/$/, '');
  if (!base) return `/books/${bookSlug}/page/${pageSlug}`;
  return `${base}/books/${bookSlug}/page/${pageSlug}`;
}

function sha256(s: string): string {
  return createHash('sha256').update(s, 'utf8').digest('hex');
}

function packFloat32(arr: Float32Array): Uint8Array {
  // Build the bytes through a fresh ArrayBuffer (not SharedArrayBuffer) so
  // Prisma's Bytes type-check is happy. Buffer.allocUnsafe sometimes
  // returns a Buffer backed by ArrayBufferLike, which trips the strict
  // Uint8Array<ArrayBuffer> requirement on the generated client.
  const ab = new ArrayBuffer(arr.length * 4);
  const view = new DataView(ab);
  for (let i = 0; i < arr.length; i++) view.setFloat32(i * 4, arr[i], true);
  return new Uint8Array(ab);
}

function unpackFloat32(blob: Uint8Array, dims: number): Float32Array {
  // Use DataView so we don't depend on the underlying ArrayBufferLike
  // variance — works for both Buffer and plain Uint8Array.
  const view = new DataView(blob.buffer, blob.byteOffset, blob.byteLength);
  const arr = new Float32Array(dims);
  for (let i = 0; i < dims; i++) arr[i] = view.getFloat32(i * 4, true);
  return arr;
}

function dotProduct(a: Float32Array, b: Float32Array): number {
  const n = Math.min(a.length, b.length);
  let s = 0;
  for (let i = 0; i < n; i++) s += a[i] * b[i];
  return s;
}

function l2Normalize(v: Float32Array): Float32Array {
  let sumSq = 0;
  for (let i = 0; i < v.length; i++) sumSq += v[i] * v[i];
  const mag = Math.sqrt(sumSq);
  if (mag === 0) return v;
  const out = new Float32Array(v.length);
  for (let i = 0; i < v.length; i++) out[i] = v[i] / mag;
  return out;
}

export const kbIndexService = new KbIndexService();
export default kbIndexService;
