-- collections_subscription EXTRACT (CRM, read-only)
-- Grain: one row per (recurring invoice, service billed on it), window-bound by
-- :pFromDate / :pToDate on the INVOICE's OrderDate. The task and campaign are NOT
-- resolved here — the transform inherits them from ie_fact_collections_invoice.
--
-- THE INVOICE IS THE BASIS. THE BILLING GROUP IS NOT.
-- This extract used to walk tblTask -> tblOrders ON o.BillingGroupID =
-- t.BillingGroupID -> tblOrderParts -> tblService, i.e. every order EVER placed on
-- the task's billing group. A billing group is a card, not an account, so that
-- collected services the cycle never billed, and it missed services whose
-- activating order sits on a different group from the task. Measured on Declined
-- CC (1st), September 2026 (377 invoices):
--
--   1,323  services the invoices actually billed   (tblRecurringItems)
--     961  services the old walk produced
--     594  in both
--     367  counted but never billed this cycle     (false positives)
--     729  billed but missed entirely              (false negatives)
--
-- Only 45% of what it reported was genuinely on those invoices, and the two errors
-- partly cancelled, which is why the total looked plausible. No downstream filter
-- can repair a set the extract never collected.
--
-- tblRecurringItems IS THE RUN'S OWN ITEM LIST: the rows the recurring run billed,
-- keyed to the invoice it generated by newOrderID (indexed) and naming the service
-- by ServiceID. It is exactly one row per service per invoice — 1,323 rows for
-- those 1,323 services, no fan-out. collections_invoice.extract.sql already reads
-- this table to resolve the charged billing group, so the key is proven.
--
-- RECURRING ONLY (OrderTypeID = 3). This section reports the recurring runs, and
-- only a recurring run has items. Order types 1 (Order) and 6 (Reactivation) carry
-- no run and are deliberately out of scope rather than linked by a second rule.
--
-- order_id IS THE BILLING ORDER — the invoice itself, so it joins straight to
-- ie_fact_collections_invoice.order_id. It previously held the order that ACTIVATED
-- the service, which matched no invoice and could not be joined to anything.
--
-- billing_group_id IS THE GROUP THE RUN CHARGED (ri.BillingGroupID), not the order
-- header: CRM rewrites tblOrders.BillingGroupID to whichever group later PAID, which
-- collections_invoice.extract.sql documents at length.
--
-- OUTCOME IS ANCHORED ON THE INVOICE DATE, which for a recurring run is the day the
-- card was charged and the day any resulting task was raised. Termination counts
-- against the cycle only when recorded on/after that date and within 180 days.
SELECT /*+ MAX_EXECUTION_TIME(180000) */
  ri.ServiceID                                 AS service_id,
  ri.BillingGroupID                            AS billing_group_id,
  ri.CustomerID                                AS customer_id,
  ri.newOrderID                                AS order_id,
  -- The part on THIS invoice, pairing with order_id above, not the activating part.
  ri.newOrderPartID                            AS order_part_id,
  s.ServiceStatus                              AS service_status,
  -- REACTIVATED MEANS A SUCCESSOR SERVICE EXISTS, not that ReactivatedDate looks
  -- recent. That column holds only the service's LATEST reactivation, and a
  -- reactivated service resumes being billed, so on every invoice that follows the
  -- date already sits in the past: it post-dates the termination on 138 of 14,615
  -- terminated services (0.9%), which is why the outcome read as zero once this
  -- extract was anchored on the invoice.
  --
  -- CRM records the succession two ways and they only partly overlap, so both are
  -- read: NextServiceID reaches 3,987 and a new service pointing back through
  -- ReactivatedID reaches 2,521, together 4,115 of 14,612 (28%).
  --
  -- ServiceLinkID is NOT a chain despite the name and 99% population — exactly 3
  -- terminated services share one with another service.
  --
  -- The radio was the other candidate and is deliberately not used. RadioID is on
  -- 99.9% of rows and finds 3,826 comebacks, but hardware gets swapped, so the key
  -- is not stable across the very event being tracked — and it finds FEWER than the
  -- service links do. Re-tested against a radio-matching chain on 2026-09-17: every
  -- service it found that the links did not (5 on the 2026-09-01 run) already had a
  -- resolving NextServiceID, so radio matching adds reach the links do not have and
  -- costs an unstable key. Those 5 are absent here for an unrelated and correct
  -- reason — they sit on an invoice that never declined, so it is outside the
  -- cohort the transform keeps.
  --
  -- RESOLVED ONCE, BY THE JOINS BELOW, and read here and by successor_service_id
  -- from the same expression, so the outcome and the successor cannot disagree.
  CASE
    WHEN term.CreatedOn IS NOT NULL
     AND COALESCE(nx.ServiceID, rv.ServiceID) IS NOT NULL                THEN 'REACTIVATED'
    WHEN term.CreatedOn IS NOT NULL                                      THEN 'TERMINATED'
    ELSE 'RETAINED'
  END                                          AS outcome,
  term.TerminationReasonID                     AS term_reason_id,
  tr.TerminationReasonText                     AS term_reason_text,
  CASE WHEN term.TerminationReasonID IN (1, 21, 32, 33, 36) THEN 1 ELSE 0 END AS is_ar_reason,
  term.CreatedOn                               AS term_recorded_on,
  term.TerminationOn                           AS term_effective_on,
  term.CreatedBy                               AS terminated_by_crm_id,
  CASE WHEN s.ReactivatedDate > '2001-01-01' THEN s.ReactivatedDate END AS reactivated_on,
  -- WHAT it came back as, and the order that sold that successor. Unlike `order_id`
  -- above — which names the invoice THIS run billed — successor_order_id is a join
  -- key to ie_fact_collections_invoice, and it is how reactivation cash is now
  -- attributed. It replaces a billing-group match that found under a fifth of that
  -- cash, because a win-back is normally paid by a new card and so lands on a
  -- different billing group; migration
  -- 20260917210000_collections_subscription_successor carries the measurement.
  --
  -- GATED ON THE TERMINATION, so these describe a service that LEFT and came back —
  -- never a live one. A retained service can also carry a NextServiceID (an upgrade
  -- or hardware swap changes the service line without it ever lapsing), and letting
  -- that populate would invite a reader to credit recovery for a subscription that
  -- never went away. With the gate, `successor_service_id IS NOT NULL` is exactly
  -- `outcome = 'REACTIVATED'` in both directions. successor_order_id can still be
  -- NULL on a REACTIVATED row when the successor's part names no order, so it is the
  -- weaker test of the two — join on it, do not count on it.
  CASE WHEN term.CreatedOn IS NOT NULL
       THEN COALESCE(nx.ServiceID, rv.ServiceID) END AS successor_service_id,
  CASE WHEN term.CreatedOn IS NOT NULL
       THEN sop.OrderID END                          AS successor_order_id,
  -- True MRR, unchanged: the billed line normalized to ONE month by the PART's own
  -- billing cycle (tblParts.PartCycleMode via tblOrderParts.PartID) — never by the
  -- billing group, which bills monthly even when its parts do not. Modes validated
  -- against observed invoice cadence: 1 -> 1.00 months, 2 -> 3.00, 3 -> annual.
  -- Not normalizing badly overstates MRR: annual parts are a small share of LINES
  -- but a large share of DOLLARS (for June, 4% of Declined CC lines yet 35% of its
  -- billed dollars, 86% of Check's, 60% of ACH's). UnitCost is the billed price —
  -- see collections_invoice.extract.sql. Read from the part this invoice billed.
  IFNULL(op.Quantity * op.UnitCost, 0)
    / CASE prt.PartCycleMode WHEN 2 THEN 3 WHEN 3 THEN 12 ELSE 1 END AS mrr_amount,
  DATE(o.OrderDate)                            AS cohort_date
FROM tblOrders o
JOIN tblRecurringItems ri
  ON ri.newOrderID = o.OrderID
JOIN tblService s
  ON s.ServiceID = ri.ServiceID
LEFT JOIN tblOrderParts op
  ON op.OrderPartID = ri.newOrderPartID
LEFT JOIN tblParts prt
  ON prt.PartID = op.PartID
-- ── The successor, the two ways CRM records one ────────────────────────────────
-- Forward pointer first, then a service pointing back, matching the precedence the
-- outcome above documents. Neither join can fan out: ServiceID is the primary key
-- and each side resolves to at most one row, which is why the reverse arm picks
-- MIN(ServiceID) — several services can point back at one predecessor, and joining
-- all of them would multiply every row for that subscription.
LEFT JOIN tblService nx
  ON nx.ServiceID = s.NextServiceID
LEFT JOIN tblService rv
  ON rv.ServiceID = (SELECT MIN(r2.ServiceID)
                       FROM tblService r2
                      WHERE r2.ReactivatedID = s.ServiceID)
-- The successor's activating part names the order that sold it.
LEFT JOIN tblOrderParts sop
  ON sop.OrderPartID = COALESCE(nx.OrderPartID, rv.OrderPartID)
-- NO TASK IS JOINED HERE. status_at_outcome is the chasing task's status, and the
-- transform reads it from ie_fact_collections_task via the invoice's own task link.
-- Matching a task in CRM on billing group + day would fan this result set out
-- whenever a group carries more than one AR task that day (customer 122706 has
-- three on 2026-08-01), silently multiplying every service on the invoice.
LEFT JOIN tblServiceTermination term
  ON term.ServiceID = s.ServiceID
 AND term.CreatedOn >= o.OrderDate
 AND term.CreatedOn <  DATE_ADD(o.OrderDate, INTERVAL 180 DAY)
 AND NOT EXISTS (
   SELECT 1 FROM tblServiceTermination t2
   WHERE t2.ServiceID = term.ServiceID
     AND t2.CreatedOn >= o.OrderDate
     AND t2.CreatedOn <  DATE_ADD(o.OrderDate, INTERVAL 180 DAY)
     AND (t2.CreatedOn < term.CreatedOn
          OR (t2.CreatedOn = term.CreatedOn AND t2.TerminationReasonID < term.TerminationReasonID))
 )
LEFT JOIN tblServiceTermReason tr
  ON tr.TerminationReasonID = term.TerminationReasonID
WHERE o.OrderTypeID = 3
  AND o.OrderDate >= :pFromDate
  AND o.OrderDate < DATE_ADD(:pToDate, INTERVAL 1 DAY)
  AND IFNULL(ri.ServiceID, 0) > 0;
