import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Plus, Pencil, ChevronDown, ChevronRight, Trash2, Check, X } from 'lucide-react'
import { useToast } from '@/hooks/use-toast'
import { listKpis, getThresholds, setThreshold, updateThreshold, deleteThreshold, updateKpi } from '@/services/insightsService'
import type { IeKpi, IeKpiThreshold } from '@/services/insightsService'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from '@/components/ui/table'
import {
  Form, FormControl, FormField, FormItem, FormLabel, FormMessage,
} from '@/components/ui/form'
import { cn } from '@/lib/utils'
import { getKpiDef } from '@/constants/kpiDefs'

const thresholdSchema = z.object({
  goal_value:     z.coerce.number().nullable().optional(),
  warning_value:  z.coerce.number().nullable().optional(),
  critical_value: z.coerce.number().nullable().optional(),
  effective_from: z.string().min(1, 'Required'),
  effective_to:   z.string().optional(),
})
type ThresholdForm = z.infer<typeof thresholdSchema>

export default function InsightsKpiManagementPage() {
  const [expandedId, setExpandedId] = useState<number | null>(null)

  const { data: kpis = [], isLoading } = useQuery({ queryKey: ['ie-kpis'], queryFn: listKpis })

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Insights KPIs</h1>
        <p className="text-sm text-muted-foreground mt-0.5">
          Registry of every KPI generated by the Insights Engine. Expand a row to edit the
          description shown in tooltips, and to manage the operational thresholds that drive scoring.
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow className="bg-slate-50/60">
              <TableHead className="w-8" />
              <TableHead className="py-4">Code</TableHead>
              <TableHead className="py-4">Name</TableHead>
              <TableHead className="py-4">Category</TableHead>
              <TableHead className="py-4">Type</TableHead>
              <TableHead className="py-4">Format</TableHead>
              <TableHead className="py-4">Direction</TableHead>
              <TableHead className="py-4">Active</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow><TableCell colSpan={8} className="text-center py-12 text-muted-foreground">Loading...</TableCell></TableRow>
            ) : kpis.length === 0 ? (
              <TableRow><TableCell colSpan={8} className="text-center py-12 text-muted-foreground">No KPIs registered yet</TableCell></TableRow>
            ) : kpis.map(k => (
              <React.Fragment key={k.id}>
                <TableRow
                  className="hover:bg-slate-50/50 cursor-pointer"
                  onClick={() => setExpandedId(expandedId === k.id ? null : k.id)}
                >
                  <TableCell>
                    {expandedId === k.id ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                  </TableCell>
                  <TableCell className="font-mono text-[13px]">{k.kpi_code}</TableCell>
                  <TableCell className="font-medium text-[14px]">{k.kpi_name}</TableCell>
                  <TableCell className="text-[13px] text-slate-600">{k.category}</TableCell>
                  <TableCell className="text-[13px] text-slate-600">{k.formula_type}</TableCell>
                  <TableCell className="text-[13px] text-slate-600">{k.format_type}</TableCell>
                  <TableCell className="text-[13px] text-slate-600">{k.direction.replace(/_/g, ' ')}</TableCell>
                  <TableCell>
                    <span className={`w-1.5 h-1.5 rounded-full inline-block ${k.is_active ? 'bg-emerald-500' : 'bg-slate-400'}`} />
                  </TableCell>
                </TableRow>
                {expandedId === k.id && (
                  <TableRow>
                    <TableCell colSpan={8} className="bg-slate-50 px-6 py-5">
                      <div className="space-y-6">
                        <KpiDefinitionPanel kpi={k} />
                        <ThresholdSection kpiId={k.id} kpiCode={k.kpi_code} />
                      </div>
                    </TableCell>
                  </TableRow>
                )}
              </React.Fragment>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}

// ── Read-only definition panel ────────────────────────────────────────────────

function KpiDefinitionPanel({ kpi }: { kpi: IeKpi }) {
  const def = getKpiDef(kpi.kpi_code)

  return (
    <div className="space-y-4">
      <div className="flex items-baseline justify-between">
        <h4 className="text-sm font-semibold text-slate-700">Definition</h4>
        <span className="text-[11px] uppercase tracking-wide text-slate-400">Formula &amp; source: read-only</span>
      </div>

      <EditableDescription kpi={kpi} fallback={def?.description} />

      <FieldWithOverride
        label="Formula"
        catalogValue={def?.formulaPlain}
        dbValue={kpi.formula}
        mono
      />

      <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
        <FieldWithOverride
          label="Source"
          catalogValue={def?.source}
          dbValue={kpi.source_table}
        />
        <Field label="Decimals">{kpi.decimal_places}</Field>
        <Field label="Sort Order">{kpi.sort_order}</Field>
      </div>
    </div>
  )
}

/**
 * Inline editor for ie_kpi.description. Default state is read-only with a
 * pencil icon; click to expand into a textarea + Save / Cancel. Saves go to
 * PUT /insights/admin/kpis/:id and invalidate both the admin KPI list and
 * the live kpi-config the tooltips read from, so changes propagate instantly.
 */
function EditableDescription({ kpi, fallback }: { kpi: IeKpi; fallback?: string }) {
  const qc = useQueryClient()
  const { toast } = useToast()
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState<string>(kpi.description ?? '')

  const saveMut = useMutation({
    mutationFn: (description: string) => updateKpi(kpi.id, { description }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['ie-kpis'] })
      qc.invalidateQueries({ queryKey: ['ie-kpi-config'] })
      toast({ title: 'Description updated' })
      setEditing(false)
    },
    onError: () => toast({ title: 'Failed to save description', variant: 'destructive' }),
  })

  const startEdit = () => {
    setDraft(kpi.description ?? '')
    setEditing(true)
  }

  const cancelEdit = () => {
    setEditing(false)
    setDraft(kpi.description ?? '')
  }

  const hasDb        = !!kpi.description && kpi.description.trim() !== ''
  const usingFallback = !hasDb && !!fallback && fallback.trim() !== ''
  const displayText  = hasDb ? kpi.description : (usingFallback ? fallback : '—')

  return (
    <div>
      <div className="flex items-center justify-between mb-1">
        <p className="text-[11px] uppercase tracking-wide text-slate-400">Description</p>
        {!editing && (
          <button
            onClick={startEdit}
            className="inline-flex items-center gap-1 text-[11px] text-primary hover:underline"
            title="Edit description"
          >
            <Pencil size={11} /> Edit
          </button>
        )}
      </div>

      {editing ? (
        <div className="space-y-2">
          <Textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            rows={4}
            className="text-[13px]"
            placeholder="Plain-language description shown in KPI tooltips..."
            autoFocus
          />
          <div className="flex items-center gap-2">
            <Button
              type="button"
              size="sm"
              onClick={() => saveMut.mutate(draft.trim() || '')}
              disabled={saveMut.isPending}
            >
              <Check size={13} className="mr-1" />
              {saveMut.isPending ? 'Saving...' : 'Save'}
            </Button>
            <Button type="button" variant="outline" size="sm" onClick={cancelEdit}>
              <X size={13} className="mr-1" /> Cancel
            </Button>
          </div>
        </div>
      ) : (
        <>
          <div
            className={cn(
              'text-[13px] bg-white border border-slate-200 rounded-md px-3 py-2 whitespace-pre-wrap',
              hasDb ? 'text-slate-700' : 'text-slate-400 italic',
            )}
          >
            {displayText}
          </div>
          {usingFallback && (
            <p className="mt-1 text-[10.5px] text-slate-400">
              No description saved yet — tooltips fall back to the bundled catalog text above. Click Edit to save your own copy.
            </p>
          )}
        </>
      )}
    </div>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="text-[11px] uppercase tracking-wide text-slate-400 mb-1">{label}</p>
      <div className="text-[13px] text-slate-600 bg-white border border-slate-200 rounded-md px-3 py-2">
        {children}
      </div>
    </div>
  )
}

/**
 * Renders a read-only field that prefers a curated catalog value but also
 * surfaces the raw DB value (greyed) when the two differ. This makes drift
 * obvious so we can decide whether to also patch the DB row.
 */
function FieldWithOverride({
  label,
  catalogValue,
  dbValue,
  mono,
  dbAsHtml,
}: {
  label: string
  catalogValue?: string | null
  dbValue?: string | null
  mono?: boolean
  dbAsHtml?: boolean
}) {
  const hasCatalog = !!catalogValue && catalogValue.trim() !== ''
  const hasDb      = !!dbValue && dbValue.trim() !== ''
  const activeText = hasCatalog ? catalogValue : (hasDb ? dbValue : '—')
  const showDbDrift = hasCatalog && hasDb && catalogValue !== dbValue

  return (
    <div>
      <div className="flex items-baseline gap-2 mb-1">
        <p className="text-[11px] uppercase tracking-wide text-slate-400">{label}</p>
        {hasCatalog && (
          <span className="text-[10px] uppercase tracking-wide text-emerald-600 bg-emerald-50 border border-emerald-100 rounded px-1.5 py-px">
            Catalog
          </span>
        )}
      </div>
      <div className={cn(
        'text-[13px] text-slate-700 bg-white border border-slate-200 rounded-md px-3 py-2 whitespace-pre-wrap',
        mono && 'font-mono text-[12.5px]',
      )}>
        {activeText}
      </div>
      {showDbDrift && (
        <div className="mt-1.5 pl-2 border-l-2 border-slate-200">
          <p className="text-[10px] uppercase tracking-wide text-slate-400 mb-0.5">DB record (drift)</p>
          {dbAsHtml ? (
            <div
              className="text-[12px] text-slate-400 italic [&_p]:my-0.5"
              dangerouslySetInnerHTML={{ __html: dbValue ?? '' }}
            />
          ) : (
            <p className={cn(
              'text-[12px] text-slate-400 italic whitespace-pre-wrap',
              mono && 'font-mono text-[11.5px] not-italic',
            )}>
              {dbValue}
            </p>
          )}
        </div>
      )}
    </div>
  )
}

// ── Thresholds (still editable — operational dial) ────────────────────────────

const PACE_BASED_KPIS = new Set(['audits_assigned', 'coaching_sessions_assigned'])

function ThresholdSection({ kpiId, kpiCode }: { kpiId: number; kpiCode: string }) {
  const qc = useQueryClient()
  const { toast } = useToast()
  const [formMode, setFormMode] = useState<'closed' | 'add' | 'edit'>('closed')
  const [editingId, setEditingId] = useState<number | null>(null)
  const isPaceBased = PACE_BASED_KPIS.has(kpiCode)

  const { data: thresholds = [] } = useQuery({ queryKey: ['ie-thresholds', kpiId], queryFn: () => getThresholds(kpiId) })

  const form = useForm<ThresholdForm>({
    resolver: zodResolver(thresholdSchema),
    defaultValues: { effective_from: new Date().toISOString().split('T')[0] },
  })

  function openAdd() {
    form.reset({ effective_from: new Date().toISOString().split('T')[0] })
    setEditingId(null)
    setFormMode('add')
  }

  function openEdit(t: IeKpiThreshold) {
    form.reset({
      goal_value:     t.goal_value     ?? undefined,
      warning_value:  t.warning_value  ?? undefined,
      critical_value: t.critical_value ?? undefined,
      effective_from: t.effective_from,
      effective_to:   t.effective_to   ?? undefined,
    })
    setEditingId(t.id)
    setFormMode('edit')
  }

  function closeForm() { setFormMode('closed'); setEditingId(null); form.reset() }

  const saveMut = useMutation({
    mutationFn: (v: ThresholdForm) =>
      formMode === 'edit' && editingId !== null
        ? updateThreshold(kpiId, editingId, v)
        : setThreshold(kpiId, v),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['ie-thresholds', kpiId] })
      toast({ title: formMode === 'edit' ? 'Threshold updated' : 'Threshold saved' })
      closeForm()
    },
  })

  const deleteMut = useMutation({
    mutationFn: (thresholdId: number) => deleteThreshold(kpiId, thresholdId),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['ie-thresholds', kpiId] })
      toast({ title: 'Threshold deleted' })
    },
  })

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <h4 className="text-sm font-semibold text-slate-700">Thresholds</h4>
        <Button size="sm" variant="outline" className="h-7 text-[12px]" onClick={openAdd} disabled={formMode !== 'closed'}>
          <Plus size={12} className="mr-1" /> Add Threshold
        </Button>
      </div>
      {isPaceBased && (
        <p className="text-[12px] text-primary bg-blue-50 border border-blue-100 rounded-md px-3 py-2">
          <strong>Pace-based KPI:</strong> Goal Value = target audits per business day.
          The system multiplies this by the number of business days in the selected period to compute the assigned count.
        </p>
      )}
      {thresholds.length === 0 && formMode === 'closed' && (
        <p className="text-[13px] text-muted-foreground">No thresholds configured for this KPI.</p>
      )}
      {thresholds.length > 0 && (
        <Table>
          <TableHeader><TableRow className="bg-white">
            <TableHead className="py-2 text-[12px]">Department</TableHead>
            <TableHead className="py-2 text-[12px]">{isPaceBased ? 'Per Business Day' : 'Goal'}</TableHead>
            <TableHead className="py-2 text-[12px]">Warning</TableHead>
            <TableHead className="py-2 text-[12px]">Critical</TableHead>
            <TableHead className="py-2 text-[12px]">From</TableHead>
            <TableHead className="py-2 text-[12px]">To</TableHead>
            <TableHead className="py-2 w-16" />
          </TableRow></TableHeader>
          <TableBody>
            {thresholds.map((t: IeKpiThreshold) => (
              <TableRow key={t.id} className={editingId === t.id ? 'bg-blue-50' : undefined}>
                <TableCell className="text-[13px]">{t.department_name ?? 'Global'}</TableCell>
                <TableCell className="text-[13px]">{t.goal_value ?? '—'}</TableCell>
                <TableCell className="text-[13px]">{t.warning_value ?? '—'}</TableCell>
                <TableCell className="text-[13px]">{t.critical_value ?? '—'}</TableCell>
                <TableCell className="text-[13px]">{t.effective_from}</TableCell>
                <TableCell className="text-[13px]">{t.effective_to ?? '—'}</TableCell>
                <TableCell>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => openEdit(t)}
                      disabled={formMode !== 'closed'}
                      className="p-1 text-slate-400 hover:text-primary disabled:opacity-30 transition-colors"
                      title="Edit"
                    >
                      <Pencil size={13} />
                    </button>
                    <button
                      onClick={() => deleteMut.mutate(t.id)}
                      disabled={deleteMut.isPending}
                      className="p-1 text-slate-400 hover:text-red-500 disabled:opacity-30 transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={13} />
                    </button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      )}
      {formMode !== 'closed' && (
        <Form {...form}>
          <form onSubmit={form.handleSubmit(v => saveMut.mutate(v))} className="bg-white rounded-lg border p-3 space-y-3">
            <p className="text-[12px] font-medium text-slate-600">{formMode === 'edit' ? 'Edit Threshold' : 'New Threshold'}</p>
            <div className="grid grid-cols-3 gap-3">
              <FormField control={form.control} name="goal_value" render={({ field }) => (
                <FormItem>
                  <FormLabel className="text-[12px]">{isPaceBased ? 'Per Business Day' : 'Goal'}</FormLabel>
                  <FormControl><Input type="number" step="any" {...field} value={field.value ?? ''} /></FormControl>
                </FormItem>
              )} />
              <FormField control={form.control} name="warning_value" render={({ field }) => (
                <FormItem><FormLabel className="text-[12px]">Warning</FormLabel><FormControl><Input type="number" step="any" {...field} value={field.value ?? ''} /></FormControl></FormItem>
              )} />
              <FormField control={form.control} name="critical_value" render={({ field }) => (
                <FormItem><FormLabel className="text-[12px]">Critical</FormLabel><FormControl><Input type="number" step="any" {...field} value={field.value ?? ''} /></FormControl></FormItem>
              )} />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <FormField control={form.control} name="effective_from" render={({ field }) => (
                <FormItem><FormLabel className="text-[12px]">Effective From</FormLabel><FormControl><Input type="date" {...field} /></FormControl><FormMessage /></FormItem>
              )} />
              <FormField control={form.control} name="effective_to" render={({ field }) => (
                <FormItem><FormLabel className="text-[12px]">Effective To</FormLabel><FormControl><Input type="date" {...field} /></FormControl></FormItem>
              )} />
            </div>
            <div className="flex gap-2">
              <Button type="button" variant="outline" size="sm" onClick={closeForm}>Cancel</Button>
              <Button type="submit" size="sm" disabled={saveMut.isPending}>
                {saveMut.isPending ? 'Saving...' : formMode === 'edit' ? 'Update' : 'Save'}
              </Button>
            </div>
          </form>
        </Form>
      )}
    </div>
  )
}
